<?php
/**
 * Created by PhpStorm.
 * User: damaha
 * Date: 20.12.2016
 * Time: 16:25
 */
IncludeModuleLangFile(__FILE__);
class damaha_directories extends CModule
{
	var $MODULE_ID = "damaha.directories";
	var $MODULE_NAME;
	var $MODULE_DESCRIPTION;
	var $PARTNER_NAME;
	var $MODULE_VERSION;
	var $MODULE_VERSION_DATE;

	function damaha_directories(){
		$arModuleVersion = array();

		$path = str_replace("\\", "/", __FILE__);
		$path = substr($path, 0, strlen($path) - strlen("/index.php"));
		include($path."/version.php");

		if (is_array($arModuleVersion) && array_key_exists("VERSION", $arModuleVersion))
		{
			$this->MODULE_VERSION = $arModuleVersion["VERSION"];
			$this->MODULE_VERSION_DATE = $arModuleVersion["VERSION_DATE"];
		}
		else
		{
			$this->MODULE_VERSION = IBLOCK_VERSION;
			$this->MODULE_VERSION_DATE = IBLOCK_VERSION_DATE;
		}

		$this->MODULE_NAME = GetMessage("IBLOCK_INSTALL_NAME");
		$this->MODULE_DESCRIPTION = GetMessage("IBLOCK_INSTALL_DESCRIPTION");
		$this->PARTNER_NAME = GetMessage("PARTNER_NAME");
	}

	function DoInstall()
	{
		global $DB, $APPLICATION, $step;
		$APPLICATION->IncludeAdminFile(GetMessage("FORM_INSTALL_TITLE"), $_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/damaha.directories/install/step1.php");
	}
	function DoUninstall()
	{
		parent::DoUninstall(); // TODO: Change the autogenerated stub
	}
}